Update before_script in OSX travis to forcibly link gcc (#507)
Otherwise we obtain the following linking failure:

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
  rm '/usr/local/include/c++'
  To force the link and overwrite all conflicting files:
    brew link --overwrite gcc
    To list all files that would be deleted:
      brew link --overwrite --dry-run gcc
      Possible conflicting files are:
      /usr/local/include/c++ ->
      /usr/local/Caskroom/oclint/0.13.1,17.4.0/oclint-0.13.1/include/c++

(cherry picked from commit de6863aa5fee0703731fe464eb7a96af3ee8d487)