Correct H50get_info deprecation for earlier releases (#510)
* Update before_script in OSX travis to forcibly link gcc

Otherwise we obtain the following linking failure:

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
  rm '/usr/local/include/c++'
  To force the link and overwrite all conflicting files:
    brew link --overwrite gcc
    To list all files that would be deleted:
      brew link --overwrite --dry-run gcc
      Possible conflicting files are:
      /usr/local/include/c++ ->
      /usr/local/Caskroom/oclint/0.13.1,17.4.0/oclint-0.13.1/include/c++

* Correct H50get_info deprecation for earlier releases

This function was renamed/deprecated in hdf5 releases newer than 10.2.
Here we update the function to map to the old realase behavior for the
latest hdf5 versions.